# @package _global_

defaults:
  - aug@aug_s: ident
  - aug@aug_u: ident

hydra:
  hydra_logging:
    disable_existing_loggers: false
  run:
    dir: .
  output_subdir: ${path.tensorboard_path}/hydra

hardware:
  nb_cpu: 4
  nb_gpu: 1

dataset:
  dataset: ubs8k
  num_classes: 10

model:
  model: wideresnet28_2

train_param:
  supervised_ratio: 0.1
  batch_size: 64
  nb_epoch: 300
  learning_rate: 0.0005
  seed: 1234
  resume: false

  # These two parameters bellow are used for UrbanSound8k and ESC cross validation
  train_folds: [1,2,3,4,5,6,7,8,9]
  val_folds: [10]

# Mean teacher parameters
dct:
  epsilon: 0.02
  warmup_length: 160
  lambda_cot_max: 1
  lambda_diff_max: 0.5

# MixUp parameters
mixup:
  use: true
  alpha: 1.0
  max: true
  label: true

path:
  dataset_root: datasets
  checkpoint_root: model_save
  tensorboard_root: tensorboard
  checkpoint_path: ${path.checkpoint_root}/${dataset.dataset}/deep-co-training
  tensorboard_path: ${path.tensorboard_root}/${dataset.dataset}/deep-co-training

tag: "NOTAG"
resume: null
download: false
