# @package _global_

defaults:
  - aug@stu_aug: ident
  - aug@tea_aug: ident

hydra:
  hydra_logging:
    disable_existing_loggers: false
  run:
    dir: .
  # Set args save in board dir
  output_subdir: ${path.tensorboard_path}/hydra

hardware:
  nb_cpu: 4
  nb_gpu: 1

dataset:
  dataset: gsc
  num_classes: 35

model:
  model: wideresnet28_2

train_param:
  supervised_ratio: 0.1
  batch_size: 64
  nb_epoch: 200
  learning_rate: 0.001
  seed: 1234
  resume: false

  # These two parameters bellow are used for UrbanSound8k and ESC cross validation
  train_folds: null
  val_folds: null

# Mean teacher parameters
mt:
  alpha: 0.999
  warmup_length: 50
  lambda_ccost_max: 1
  use_softmax: true
  ccost_method: mse
  noise_db: 0.0

# MixUp parameters
mixup:
  use: true
  alpha: 1.0
  max: true
  label: true

path:
  dataset_root: datasets
  tensorboard_root: tensorboard
  tensorboard_path: ${path.tensorboard_root}/${dataset.dataset}/mean-teacher

tag: "NOTAG"
resume: null
download: false
